[package]
name = "depo-scraper"
version = "0.2.1"
edition = "2018"  # Use Rust 2018 edition

[dependencies]
clipboard = "0.5"
warp = "0.3.7"  # for HTTP server
tokio = { version = "1.43", features = ["full"] }  # asynchronous runtime for warp
